### ISSUE TITLE
Should we run tsnode in production?

### ISSUE THREAD

**Issue by nrutledge** [nrutledge/pocket-clone#3]

**Comment by Benjmhart** [comment]
it looks like the answer is, yes, with a small memory overhead

https://github.com/TypeStrong/ts-node/issues/104

something like:
` ts-node --transpile-only server.ts`

alternatively we add a build step & run normal node on the transpiled code

**Comment by Benjmhart** [comment]
alternative viewpoint: https://www.reddit.com/r/typescript/comments/8vkvzy/typescript_with_node_should_i_use_tsnode_or_tsc/?st=jxuc3o3z&sh=2905b259

**Comment by Benjmhart** [comment]
https://medium.com/javascript-in-plain-english/typescript-with-node-and-express-js-why-when-and-how-eb6bc73edd5d
